### PR TITLE
Changed JPG to PNG, invert nighttime Meteor M2 images and fixed timezone issues

### PR DESCRIPTION
**Pull request by MihajloPi**
I've changed all receive scripts and rectify.py to work exclusively with PNG instead of JPG format in order to preserve the resolution. Nighttime Meteor M2 passes are inverted in colour so that clouds remain white, and not black. Fixed issue with timezones I have had (when I input +2, program calculates sun elevation for -2 timezone).

### CODE REVIEW

**Comment by ghost** [comment]
@mihajlo2003petkovic 

Thanks for collaborating - I've a tremendous doubt, can't understand if in sun.py file I've to put "+2" (I'm from Italy) or just "2" in the tz line...

When I've opened the file yesterday I've found the wrong value of "-2", strangely... lately, the station seems to work and receive well, probably for this value too? Can't understand why it has changed without motivation.

**Comment by MihajloPi** [comment]
Argentina is I think -2 timezone or something comparing to UTC. When I first downloaded v1.2, the script was also calculating sun elevation for -2 timezone so I just had to change it to +1 for CET (I'm from Serbia) and add time.localtime().tm_isdst to timezone value in order to automatically correct local time for DST. For some reason, even though I've input timezone during installation, it remained missing in sun.py script.

**Comment by reynico** [comment]
Hi @mihajlo2003petkovic ! Thanks for the time you invested here.


Ain't `-rotate 180` missing here?
https://github.com/reynico/raspberry-noaa/pull/49/commits/af1772fb2ac8db499e60c1fac338e42b913e24e6#diff-8942e4d50aae6d815baaf2e8805d9a9c1daad883f358c85f6c34443ec6ae1a8bR58

**Comment by MihajloPi** [comment]
> Hi @mihajlo2003petkovic ! Thanks for the time you invested here.
> 
> 
> Ain't `-rotate 180` missing here?
> https://github.com/reynico/raspberry-noaa/pull/49/commits/af1772fb2ac8db499e60c1fac338e42b913e24e6#diff-8942e4d50aae6d815baaf2e8805d9a9c1daad883f358c85f6c34443ec6ae1a8bR58
> 
> 

Yes, I removed rotate by 180° because I was always getting correctly oriented images so, I never needed to rotate them even at night passes.

**Comment by MihajloPi** [comment]
I forgot to mention that I was comparing sun elevation calculated by sun.py with webpage: https://www.timeanddate.com/sun/ . That's how I found that it was not being  calculated correctly. Yoi just type in your city and it shows sun elevation in degrees.

**Comment by ghost** [comment]
@mihajlo2003petkovic 
@reynico 

Sorry folks... I'm lost. Didn't understood if now, after update, I have to put -2 / +2 or 2 here for Italy :(

OR +1 / 1 CEST?

My receptions seem not to work well anymore...

[Screenshot_20201016_210710_com.android.chrome.jpg](https://user-images.githubusercontent.com/26116552/96298966-98cd6800-0ff3-11eb-9a70-35ac8d1a1e3a.jpg)

**Pull request merged**
